export enum MVRProcessingStatus {
  COMPLETED_VERISK_SYNC = 'COMPLETED-VERISK-SYNC',
  FAILED_VERISK_SYNC = 'FAILED-VERISK-SYNC',
  FAILED_SYNC_MVR_PDF_SALESFORCE = 'FAILED-SYNC-MVR-PDF-SALESFORCE',
  SALESFORCE_PDF_SYNCED = 'SALESFORCE-PDF-SYNCED',
}